"""create table xlc_offline

Revision ID: 181e59c29aa0
Revises: 4502b5852756
Create Date: 2025-12-31 15:56:17.969483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '181e59c29aa0'
down_revision: Union[str, Sequence[str], None] = '4502b5852756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xlcoffline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hostname22', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('connection', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('network_priority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('genset_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ups_inventer_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receiver_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receiver_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('battery_backup_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('route_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('main_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('affected_device', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lease_expired', sa.Date(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('column1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('column2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('host3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activity_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xlcoffline')
    # ### end Alembic commands ###
