"""create table schedule

Revision ID: 4502b5852756
Revises: 9916784ac512
Create Date: 2025-12-31 15:28:53.374251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4502b5852756'
down_revision: Union[str, Sequence[str], None] = '9916784ac512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senin_open', sa.Time(), nullable=True),
    sa.Column('senin_close', sa.Time(), nullable=True),
    sa.Column('selasa_open', sa.Time(), nullable=True),
    sa.Column('selasa_close', sa.Time(), nullable=True),
    sa.Column('rabu_open', sa.Time(), nullable=True),
    sa.Column('rabu_close', sa.Time(), nullable=True),
    sa.Column('kamis_open', sa.Time(), nullable=True),
    sa.Column('kamis_close', sa.Time(), nullable=True),
    sa.Column('jumat_open', sa.Time(), nullable=True),
    sa.Column('jumat_close', sa.Time(), nullable=True),
    sa.Column('sabtu_open', sa.Time(), nullable=True),
    sa.Column('sabtu_close', sa.Time(), nullable=True),
    sa.Column('minggu_open', sa.Time(), nullable=True),
    sa.Column('minggu_close', sa.Time(), nullable=True),
    sa.Column('national_holiday_open', sa.Time(), nullable=True),
    sa.Column('national_holiday_close', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
