"""create table national_holiday

Revision ID: 96ba2a84865b
Revises: 181e59c29aa0
Create Date: 2025-12-31 16:14:27.762336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96ba2a84865b'
down_revision: Union[str, Sequence[str], None] = '181e59c29aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('national_holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('national_holiday')
    # ### end Alembic commands ###
